services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ZeroTwoDryOrc5166
      - MSSQL_PID=Developer
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: